apiVersion: apps/v1
kind: Deployment
metadata:
  name: p1-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: p1-devops
  template:
    metadata:
      labels:
        app: p1-devops
    spec:
      containers:
        - name: p1-devops
          image: gustavokubiack/p1-devops
          ports:
            - containerPort: 8000
