apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: gustavokubiack/p1-devops
  newName: gustavokubiack/p1-devops
  newTag: 0ca11bb21971413f14722c9130d957fa80ee0280
- name: p1-devops
  newName: gustavokubiack/p1-devops
  newTag: 74663fd74c1aed93cc3515856e660acc32387899
