apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: p1-devops
    newName: gustavokubiack/p1-devops
    newTag: 74663fd74c1aed93cc3515856e660acc32387899